config/routes.rb
Engdb::Application.routes.draw do

  resources :capa_files

  resources :capas

  resources :bulletin_files

  resources :treq_files

  resources :request_files

  resources :gages

  mount Forem::Engine, :at => '/forums'

  resources :product_bulletins

  resources :treqs

  resources :engineering_procedures

  resources :engineering_projects

  resources :request_items

  resources :requests

  resources :email_lists

get 'home' => 'home#index'
get 'logout' => 'sessions#destroy'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

  get "login/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  get "home/index"
  
  get '/home', to: 'home#index', as: 'home'

  
  resources :ecns do
    resources :revisions
  end

  resources :revisions
  match '/drawings/new', to: 'drawings#new', as: 'new_drawing'
  match '/drawings/newe', to: 'drawings#new_e_drawing', as: 'new_e_drawing'
  match '/drawings/newrd', to: 'drawings#new_rd_drawing', as: 'new_rd_drawing'
  match '/drawings/newwp', to: 'drawings#new_wp_drawing', as: 'new_wp_drawing'

  resources :drawings do
    resources :revisions
    
  end
  
  resources :home
  

 match 'ecns/submit' => 'ecns#submit'
 match 'ecns/close' => 'ecns#close'
 match 'ecns/index_open' => 'ecns#index_open'
 
 match 'requests/submit_eng' => 'requests#submit_eng'
 match 'requests/index_open' => 'requests#index_open'
 match 'requests/submit_mfg' => 'requests#submit_mfg'
 match 'requests/submit_acct' => 'requests#submit_acct'
 match 'requests/submit_sales' => 'requests#submit_sales'
 match 'requests/submit_sor' => 'requests#submit_sor'
 match 'requests/reject' => 'requests#reject'
 match 'requests/close' => 'requests#close'
 match 'requests/close_sir' => 'requests#close_sir'
 match 'requests/download' => 'requests#download'
 
 match 'product_bulletins/download' => 'product_bulletins#download'
 match 'treqs/download' => 'treqs#download'
 
 match 'drawings/view' => 'drawings#view'
 
 match 'capas/download' => 'capas#download'
 match 'capas/assign' => 'capas#assign'
 match 'capas/resolve' => 'capas#resolve'
 match 'capas/close' => 'capas#close'
 match 'capas/followup' => 'capas#followup'
 
 get '/users/sign_in', :to => "users#sign_in"
 get 'request_items/download'

    root :to => 'sessions#new'

end

app/models/treq_file.rb
class TreqFile < ActiveRecord::Base
  attr_accessible :file, :treq_id  
  mount_uploader :file, FileUploader
  belongs_to :treq
end

app/controllers/treq_files_controller.rb
class TreqFilesController < ApplicationController
  # GET /treq_files
  # GET /treq_files.json
  def index
    @treq_files = TreqFile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @treq_files }
    end
  end

  # GET /treq_files/1
  # GET /treq_files/1.json
  def show
    @treq_file = TreqFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @treq_file }
    end
  end

  # GET /treq_files/new
  # GET /treq_files/new.json
  def new
    @treq_file = TreqFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @treq_file }
    end
  end

  # GET /treq_files/1/edit
  def edit
    @treq_file = TreqFile.find(params[:id])
  end

  # POST /treq_files
  # POST /treq_files.json
  def create
    @treq_file = TreqFile.new(params[:treq_file])

    respond_to do |format|
      if @treq_file.save
        
        format.html { redirect_to @treq_file, notice: 'Treq file was successfully created.' }
        format.json { render json: @treq_file, status: :created, location: @treq_file }
      else
        format.html { render action: "new" }
        format.json { render json: @treq_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /treq_files/1
  # PUT /treq_files/1.json
  def update
    @treq_file = TreqFile.find(params[:id])

    respond_to do |format|
      if @treq_file.update_attributes(params[:treq_file])
        format.html { redirect_to @treq_file, notice: 'Treq file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @treq_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treq_files/1
  # DELETE /treq_files/1.json
  def destroy
    @treq_file = TreqFile.find(params[:id])
    @treq_file.destroy

    respond_to do |format|
      format.html { redirect_to treq_files_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/treq_files_helper.rb
module TreqFilesHelper
end

app/views/treq_files/_form.html.erb
<%= form_for(@treq_file) do |f| %>
  <% if @treq_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treq_file.errors.count, "error") %> prohibited this treq_file from being saved:</h2>

      <ul>
      <% @treq_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :treq_id %><br />
    <%= f.number_field :treq_id %>
  </div>
  <div class="field">
    <%= f.label :file %><br />
    <%= f.text_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/treq_files/edit.html.erb
<h1>Editing treq_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @treq_file %> |
<%= link_to 'Back', treq_files_path %>

app/views/treq_files/index.html.erb
<h1>Listing treq_files</h1>

<table>
  <tr>
    <th>Treq</th>
    <th>File</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @treq_files.each do |treq_file| %>
  <tr>
    <td><%= treq_file.treq_id %></td>
    <td><%= treq_file.file %></td>
    <td><%= link_to 'Show', treq_file %></td>
    <td><%= link_to 'Edit', edit_treq_file_path(treq_file) %></td>
    <td><%= link_to 'Destroy', treq_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Treq file', new_treq_file_path %>

app/views/treq_files/new.html.erb
<h1>New treq_file</h1>

<%= render 'form' %>

<%= link_to 'Back', treq_files_path %>

app/views/treq_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Treq:</b>
  <%= @treq_file.treq_id %>
</p>

<p>
  <b>File:</b>
  <%= @treq_file.file %>
</p>


<%= link_to 'Edit', edit_treq_file_path(@treq_file) %> |
<%= link_to 'Back', treq_files_path %>