config/routes.rb
Engdb::Application.routes.draw do

  resources :capa_files

  resources :capas

  resources :bulletin_files

  resources :treq_files

  resources :request_files

  resources :gages

  mount Forem::Engine, :at => '/forums'

  resources :product_bulletins

  resources :treqs

  resources :engineering_procedures

  resources :engineering_projects

  resources :request_items

  resources :requests

  resources :email_lists

get 'home' => 'home#index'
get 'logout' => 'sessions#destroy'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

  get "login/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  get "home/index"
  
  get '/home', to: 'home#index', as: 'home'

  
  resources :ecns do
    resources :revisions
  end

  resources :revisions
  match '/drawings/new', to: 'drawings#new', as: 'new_drawing'
  match '/drawings/newe', to: 'drawings#new_e_drawing', as: 'new_e_drawing'
  match '/drawings/newrd', to: 'drawings#new_rd_drawing', as: 'new_rd_drawing'
  match '/drawings/newwp', to: 'drawings#new_wp_drawing', as: 'new_wp_drawing'

  resources :drawings do
    resources :revisions
    
  end
  
  resources :home
  

 match 'ecns/submit' => 'ecns#submit'
 match 'ecns/close' => 'ecns#close'
 match 'ecns/index_open' => 'ecns#index_open'
 
 match 'requests/submit_eng' => 'requests#submit_eng'
 match 'requests/index_open' => 'requests#index_open'
 match 'requests/submit_mfg' => 'requests#submit_mfg'
 match 'requests/submit_acct' => 'requests#submit_acct'
 match 'requests/submit_sales' => 'requests#submit_sales'
 match 'requests/submit_sor' => 'requests#submit_sor'
 match 'requests/reject' => 'requests#reject'
 match 'requests/close' => 'requests#close'
 match 'requests/close_sir' => 'requests#close_sir'
 match 'requests/download' => 'requests#download'
 
 match 'product_bulletins/download' => 'product_bulletins#download'
 match 'treqs/download' => 'treqs#download'
 
 match 'drawings/view' => 'drawings#view'
 
 match 'capas/download' => 'capas#download'
 match 'capas/assign' => 'capas#assign'
 match 'capas/resolve' => 'capas#resolve'
 match 'capas/close' => 'capas#close'
 match 'capas/followup' => 'capas#followup'
 
 get '/users/sign_in', :to => "users#sign_in"
 get 'request_items/download'

    root :to => 'sessions#new'

end

app/models/revision.rb
class Revision < ActiveRecord::Base
  belongs_to :drawing, foreign_key: :drawing_number
  belongs_to :ecn
  
  validates :drawing_number, :change, :rev_level, :disposition_wip, :disposition_inventory, presence: true
  
  DISPOSITION_TYPES = [ "N/A", "Use As Is", "Scrap", "Rework", "No Impact" ]
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  before_filter :eng_check, only: [:new, :create, :update, :destroy]
  # GET /revisions
  # GET /revisions.json
  def index
    @revisions = Revision.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @revisions }
    end
  end

  # GET /revisions/1
  # GET /revisions/1.json
  def show
    @revision = Revision.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @revision }
    end
  end

  # GET /revisions/new
  # GET /revisions/new.json
  def new
    @revision = Revision.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @revision }
    end
  end

  # GET /revisions/1/edit
  def edit
    @revision = Revision.find(params[:id])
  end

  # POST /revisions
  # POST /revisions.json
  def create
    
    @revision = Revision.new(params[:revision])

    respond_to do |format|
      if @revision.save
        format.html { redirect_to @revision, notice: 'Revision was successfully created.' }
        format.json { render json: @revision, status: :created, location: @revision }
      else
        format.html { render action: "new" }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /revisions/1
  # PUT /revisions/1.json
  def update
    @revision = Revision.find(params[:id])

    respond_to do |format|
      if @revision.update_attributes(params[:revision])
        format.html { redirect_to @revision, notice: 'Revision was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revisions/1
  # DELETE /revisions/1.json
  def destroy
    @revision = Revision.find(params[:id])
    @revision.destroy

    respond_to do |format|
      format.html { redirect_to revisions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/views/revisions/_form.html.erb
<%= form_for :revisions, :url => { :controller => "revisions", :action => "create" } do |f| %>

  <div class="revfield">
    <b><%= f.label :drawing_number %></b><br />
    <%= f.text_field :drawing_number %>
  </div>
  <div class="field">
    <%= f.label :change %><br />
    <%= f.text_area :change, rows: 3 %>
  </div>
  <div class="field">
    <%= f.label :justification %><br />
    <%= f.text_area :justification, rows: 3 %>
  </div>
  <div class="field">
    <%= f.label :rev_level %><br />
    <%= f.text_field :rev_level %>
  </div>
  <div class="field">
    <%= f.label :disposition_wip %><br />
    <%= f.text_field :disposition_wip %>
  </div>
  <div class="field">
    <%= f.label :disposition_inventory %><br />
    <%= f.text_field :disposition_inventory %>
  </div>
  <div class="field">
    <%= f.label :quantity_in_qantel %><br />
    <%= f.number_field :quantity_in_qantel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/revisions/edit.html.erb
<h1>Editing revision</h1>

<%= render 'form' %>

<%= link_to 'Show', @revision %> |
<%= link_to 'Back', revisions_path %>

app/views/revisions/index.html.erb
<h1>Listing revisions</h1>

<table class="table table-hover">
  <tr>
    <th>Change</th>
    <th>Justification</th>
    <th>Rev level</th>
    <th>Disposition wip</th>
    <th>Disposition inventory</th>
    <th>Quantity in qantel</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @revisions.each do |revision| %>
  <tr>
    <td><%= revision.change %></td>
    <td><%= revision.justification %></td>
    <td><%= revision.rev_level %></td>
    <td><%= revision.disposition_wip %></td>
    <td><%= revision.disposition_inventory %></td>
    <td><%= revision.quantity_in_qantel %></td>
    <td><%= link_to 'Show', revision %></td>
    <td><%= link_to 'Edit', edit_revision_path(revision) %></td>
    <td><%= link_to 'Destroy', revision, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Revision', new_revision_path %>

app/views/revisions/new.html.erb
<h1>New revision</h1>

<%= render 'revisions/form' %>

app/views/revisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Change:</b>
  <%= @revision.change %>
</p>

<p>
  <b>Justification:</b>
  <%= @revision.justification %>
</p>

<p>
  <b>Rev level:</b>
  <%= @revision.rev_level %>
</p>

<p>
  <b>Disposition wip:</b>
  <%= @revision.disposition_wip %>
</p>

<p>
  <b>Disposition inventory:</b>
  <%= @revision.disposition_inventory %>
</p>

<p>
  <b>Quantity in qantel:</b>
  <%= @revision.quantity_in_qantel %>
</p>


<%= link_to 'Edit', edit_revision_path(@revision) %> |
<%= link_to 'Back', revisions_path %>