config/routes.rb
Engdb::Application.routes.draw do

  resources :capa_files

  resources :capas

  resources :bulletin_files

  resources :treq_files

  resources :request_files

  resources :gages

  mount Forem::Engine, :at => '/forums'

  resources :product_bulletins

  resources :treqs

  resources :engineering_procedures

  resources :engineering_projects

  resources :request_items

  resources :requests

  resources :email_lists

get 'home' => 'home#index'
get 'logout' => 'sessions#destroy'
get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

  get "login/index"

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  resources :users

  get "home/index"
  
  get '/home', to: 'home#index', as: 'home'

  
  resources :ecns do
    resources :revisions
  end

  resources :revisions
  match '/drawings/new', to: 'drawings#new', as: 'new_drawing'
  match '/drawings/newe', to: 'drawings#new_e_drawing', as: 'new_e_drawing'
  match '/drawings/newrd', to: 'drawings#new_rd_drawing', as: 'new_rd_drawing'
  match '/drawings/newwp', to: 'drawings#new_wp_drawing', as: 'new_wp_drawing'

  resources :drawings do
    resources :revisions
    
  end
  
  resources :home
  

 match 'ecns/submit' => 'ecns#submit'
 match 'ecns/close' => 'ecns#close'
 match 'ecns/index_open' => 'ecns#index_open'
 
 match 'requests/submit_eng' => 'requests#submit_eng'
 match 'requests/index_open' => 'requests#index_open'
 match 'requests/submit_mfg' => 'requests#submit_mfg'
 match 'requests/submit_acct' => 'requests#submit_acct'
 match 'requests/submit_sales' => 'requests#submit_sales'
 match 'requests/submit_sor' => 'requests#submit_sor'
 match 'requests/reject' => 'requests#reject'
 match 'requests/close' => 'requests#close'
 match 'requests/close_sir' => 'requests#close_sir'
 match 'requests/download' => 'requests#download'
 
 match 'product_bulletins/download' => 'product_bulletins#download'
 match 'treqs/download' => 'treqs#download'
 
 match 'drawings/view' => 'drawings#view'
 
 match 'capas/download' => 'capas#download'
 match 'capas/assign' => 'capas#assign'
 match 'capas/resolve' => 'capas#resolve'
 match 'capas/close' => 'capas#close'
 match 'capas/followup' => 'capas#followup'
 
 get '/users/sign_in', :to => "users#sign_in"
 get 'request_items/download'

    root :to => 'sessions#new'

end

app/models/treq.rb
class Treq < ActiveRecord::Base
  has_many :treq_files
  accepts_nested_attributes_for :treq_files
  validates :test_number, :submitted_by, :pump_model, :description, presence: true
  validates :test_number, uniqueness: true

  scope :by_keyword, ->(keys=nil) {
    if keys.blank?
      
    else
      terms = keys.split(/\s*,\s*/).map { |t| t.strip }.map { |t| "%#{t}%" }
      where( ( ["#{table_name}.description like ?"] * terms.count).join(' and '), *terms )
    end
  }
  scope :by_pump_model, lambda { |pump_model| where('pump_model LIKE ?', "#{pump_model}%") unless pump_model.nil? }

  def incrament(treq)
    treq[:test_number] = Treq.maximum(:test_number) + 1
    return treq
  end

end

app/controllers/treqs_controller.rb
class TreqsController < ApplicationController
  handles_sortable_columns
  before_filter :eng_check, only: [:new, :create, :update, :show, :edit]
  before_filter :admin_check, only: [:destroy]
  # GET /treqs
  # GET /treqs.json
  def index
    order = sortable_column_order, "test_number desc"
    if params[:description].nil? or params[:pump_model].nil?
    @treqs = Treq.paginate page: params[:page], order: order, per_page: 50
    else
      @treqs = Treq\
      .by_keyword(params[:description])\
      .by_pump_model(params[:pump_model])\
      .paginate page: params[:page], order: order, per_page: 50
      
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @treqs }
    end
  end

  # GET /treqs/1
  # GET /treqs/1.json
  def show
    @treq = Treq.find(params[:id])
    @treq_files = @treq.treq_files.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @treq }
    end
  end

  # GET /treqs/new
  # GET /treqs/new.json
  def new
    @treq = Treq.new
    @treq = @treq.incrament(@treq)
    @treq_file = @treq.treq_files.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @treq }
    end
  end

  # GET /treqs/1/edit
  def edit
    @treq = Treq.find(params[:id])
    @treq_files = @treq.treq_files.all
    if @treq_files.blank?
      @treq_file = @treq.treq_files.build
    else
    end
  end

  # POST /treqs
  # POST /treqs.json
  def create
    @treq = Treq.new(params[:treq])
    
    respond_to do |format|
      if @treq.save
        unless params[:treq_files].blank?
          params[:treq_files]['file'].each do |a|
            @treq_file = @treq.treq_files.create!(:file => a, :treq_id => @treq.id)
          end
        end
        TreqNotifier.submit_treq(@treq).deliver
        format.html { redirect_to @treq, notice: 'Treq was successfully created.' }
        format.json { render json: @treq, status: :created, location: @treq }
      else
        format.html { render action: "new", alert: "Test Requset has been submitted."}
        format.json { render json: @treq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /treqs/1
  # PUT /treqs/1.json
  def update
    @treq = Treq.find(params[:id])

    respond_to do |format|
      unless params[:treq_files].blank?
          params[:treq_files]['file'].each do |a|
            @treq_file = @treq.treq_files.create!(:file => a, :treq_id => @treq.id)
          end
        end
      if @treq.update_attributes(params[:treq])
        format.html { redirect_to @treq, notice: 'Treq was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @treq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treqs/1
  # DELETE /treqs/1.json
  def destroy
    @treq = Treq.find(params[:id])
    @treq.destroy

    respond_to do |format|
      format.html { redirect_to treqs_url }
      format.json { head :no_content }
    end
  end
  
  def download
    @treq_file = TreqFile.where('id LIKE ?', params[:id])
    @path = @treq_file.each do |p|
      return p.file_url
    end
    @name = params[:file]
    # for windows testing
    #@file = "c://users/sabrams/engdb/public#{@name}"
    # for linux live system
    @file = "/srv/engdb/public#{@name}"
    # for home mac system
    #@file = "/users/fonmus/documents/aptana\ studio\ 3\ workspace/engdb/public#{@name}"
    send_file( @file,
    :disposition => 'inline',
    :x_sendfile => true )
   
  #rescue TypeError
  #    redirect_to @request, :flash => { :alert => "File not found.  Please try again or contact support." }
  end 

  private
   def treq_params
      params.require(:treq).permit(:treq_number, treq_attributes: [:id, :treq_id, :file])
   end
  
end

app/helpers/treqs_helper.rb
module TreqsHelper
end

app/views/treqs/_form.html.erb
<%= form_for(@treq) do |f| %>
  <% if @treq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treq.errors.count, "error") %> prohibited this treq from being saved:</h2>

      <ul>
      <% @treq.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :test_number %><br />
    <%= f.number_field :test_number %>
  </div>
  <div class="field">
    <%= f.label :date_recieved %><br />
    <%= f.date_select :date_recieved %>
  </div>
  <div class="field">
    <%= f.label :submitted_by %><br />
    <%= f.text_field :submitted_by %>
  </div>
  <div class="field">
    <%= f.label :pump_model %><br />
    <%= f.text_field :pump_model %>
  </div>
  <div class="field">
    <%= f.label :technician %><br />
    <%= f.text_field :technician %>
  </div>
  <div class="field">
    <%= f.label :date_complete %><br />
    <%= f.date_select :date_complete, {:include_blank => true, :default => nil} %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  
  <div class="clear">
  <b>Upload Files:</b>
  <%= f.fields_for :treq_files do |p| %>
     <div class="field">
       <%= p.file_field :file, :multiple => true, name: "treq_files[file][]" %>
     </div>
  <% end %>
  </div>
	
   <% if params[:controller] == "treqs" && params[:action] == "show" %> 
     <b>Uploaded Files:</b>
		<table class="table">
		<% @treq.treq_files.each do |p| %>
		  <tr>
		  	<td><%= p.file_url.split("/").last %></td>
		    <td><%= button_to "Download File", {action: "download", controller: "treqs", :file => p.file}  %></td>
		  </tr>
		<% end %>
		</table>
   <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/treqs/_treq_search.html.erb
<%= form_for :treqs, :url => { :controller => "treqs", :action => "index" }, :html => {method: :get, class: "form-inline"} do |f| %>
  <div class="field">
    <%= f.label :keywords %>
    <%= text_field_tag 'description' %>

    <%= f.label :pump_model %>
    <%= text_field_tag 'pump_model' %>

    <%= f.submit "Search" %>
  </div>
<% end %>

app/views/treqs/edit.html.erb
<h1>Edit Test Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @treq %> |
<%= link_to 'Back', treqs_path %>

app/views/treqs/index.html.erb
<h1>Test Requests</h1>

<%= render 'treq_search'%>

<%= link_to 'New Treq', new_treq_path if user_in_engineering? %>
<table class="table table-striped">
  <tr class="info">
    <th><%= sortable_column "Test number" %></th>
    <th><%= sortable_column "Date recieved" %></th>
    <th><%= sortable_column "Submitted by" %></th>
    <th><%= sortable_column "Pump model" %></th>
    <th><%= sortable_column "Technician" %></th>
    <th><%= sortable_column "Date complete" %></th>
    <th><%= sortable_column "Description" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @treqs.each do |treq| %>
  <tr>
    <td><%= link_to treq.test_number, treq %></td>
    <td><%= treq.date_recieved %></td>
    <td><%= treq.submitted_by %></td>
    <td><%= treq.pump_model %></td>
    <td><%= treq.technician %></td>
    <td><%= treq.date_complete %></td>
    <td><%= treq.description %></td>
    <td><%= link_to treq do %>
    	<i class="icon-eye-open glyphw"></i>
    	<% end %>
    	<% if user_in_engineering? %>
			<%= link_to edit_treq_path(treq) do %>
	    	<i class="icon-pencil glyphw"></i>
	    	<% end %>
	    <% end %>
	    <% if user_in_admin? %>
			<%= link_to '<i class="icon-trash glyphw"></i>'.html_safe, treq, confirm: 'Are you sure?', method: :delete %>
		<% end %>
	</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Treq', new_treq_path if user_in_engineering? %>
<p><%= will_paginate @treqs %></p>
<%= link_to 'Back', :back %>

app/views/treqs/new.html.erb
<h1>New Test Request</h1>

<%= render 'form' %>

<%= link_to 'Back', treqs_path %>

app/views/treqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Test number:</b>
  <%= @treq.test_number %>
</p>

<p>
  <b>Date recieved:</b>
  <%= @treq.date_recieved %>
</p>

<p>
  <b>Submitted by:</b>
  <%= @treq.submitted_by %>
</p>

<p>
  <b>Pump model:</b>
  <%= @treq.pump_model %>
</p>

<p>
  <b>Technician:</b>
  <%= @treq.technician %>
</p>

<p>
  <b>Date complete:</b>
  <%= @treq.date_complete %>
</p>

<p>
  <b>Description:</b>
  <%= @treq.description %>
</p>

<b>Uploaded Files:</b>
<table class="table">
<% @treq_files.each do |p| %>
  <tr>
  	<td><%= p.file_url.split("/").last unless p.file_url.nil? %></td>
    <td><%= button_to "Download File", {action: "download", controller: "treqs", :file => p.file}  %></td>
    <% if user_in_admin? %>
	  <td><%= link_to "Delete File", p, method: :delete %></td>
	<% end %>
  </tr>
<% end %>

<br>

<%= link_to 'Edit', edit_treq_path(@treq) %> |
<%= link_to 'Back', treqs_path %>